# Generated by Django 6.0.2 on 2026-03-21 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('framework_type', models.CharField(choices=[('ISO27001', 'ISO 27001'), ('GDPR', 'GDPR'), ('DPDP', 'DPDP Act (India)'), ('SOC2', 'SOC 2'), ('HIPAA', 'HIPAA'), ('PCIDSS', 'PCI DSS'), ('RBI', 'RBI Guidelines'), ('NPCI', 'NPCI Standards'), ('UIDAI', 'UIDAI/Aadhaar'), ('SEBI', 'SEBI Regulations'), ('IRDAI', 'IRDAI Guidelines')], max_length=20)),
                ('description', models.TextField()),
                ('version', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('partial', 'Partially Compliant'), ('not_assessed', 'Not Assessed')], default='not_assessed', max_length=15)),
                ('evidence', models.TextField(blank=True)),
                ('last_audit_date', models.DateTimeField(blank=True, null=True)),
                ('next_audit_date', models.DateTimeField(blank=True, null=True)),
                ('auditor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='compliance.complianceframework')),
            ],
            options={
                'ordering': ['control_id'],
            },
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditor_name', models.CharField(max_length=200)),
                ('audit_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('audit_date', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='compliance.complianceframework')),
            ],
            options={
                'ordering': ['-audit_date'],
            },
        ),
    ]
