# Generated by Django 6.0.2 on 2026-03-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancecontrol',
            name='compliance_body',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='compliancecontrol',
            name='mandatory',
            field=models.BooleanField(default=True),
        ),
    ]
