# Generated by Django 6.0.2 on 2026-03-21 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('cve_fetch', 'CVE Fetched'), ('advisory_created', 'Advisory Created'), ('alert_triggered', 'Alert Triggered'), ('vendor_updated', 'Vendor Updated'), ('compliance_check', 'Compliance Check'), ('user_action', 'User Action'), ('darkweb_scan', 'Dark Web Scan')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('client', 'Client'), ('auditor', 'Auditor'), ('analyst', 'Security Analyst')], default='client', max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar_initial', models.CharField(blank=True, max_length=2)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
