# Generated by Django 6.0.2 on 2026-03-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_action_type_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('IT', 'IT / SaaS'), ('Banking', 'Banking / Fintech'), ('Healthcare', 'Healthcare'), ('Insurance', 'Insurance'), ('Government', 'Government'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='org_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('client_admin', 'Client Admin'), ('compliance_manager', 'Compliance Manager'), ('auditor', 'Auditor'), ('vendor_user', 'Vendor User')], default='client_admin', max_length=20),
        ),
    ]
