# Generated by Django 6.0.2 on 2026-03-21 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cve_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('affected_systems', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('recommended_action', models.TextField()),
                ('source', models.CharField(choices=[('CERT-IN', 'CERT-IN'), ('AUTO', 'Auto-Generated'), ('MANUAL', 'Manual')], default='AUTO', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_cve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisories', to='cve_engine.cve')),
            ],
            options={
                'verbose_name_plural': 'Advisories',
                'ordering': ['-created_at'],
            },
        ),
    ]
