# Generated by Django 6.0.2 on 2026-03-21 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DarkWebMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('domains', models.JSONField(default=list, help_text='List of domains to monitor')),
                ('keywords', models.JSONField(default=list, help_text='Keywords to watch for')),
                ('emails', models.JSONField(default=list, help_text='Email addresses to monitor')),
                ('api_key', models.CharField(blank=True, help_text='API key for dark web service', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired')], default='active', max_length=10)),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('scan_frequency_hours', models.IntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DarkWebAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('alert_type', models.CharField(choices=[('credential_leak', 'Credential Leak'), ('data_breach', 'Data Breach'), ('mention', 'Organization Mention'), ('paste', 'Paste Site Detection'), ('market', 'Dark Market Listing'), ('ransomware', 'Ransomware Group')], default='mention', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('confirmed', 'Confirmed'), ('false_positive', 'False Positive'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('affected_assets', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='darkweb.darkwebmonitor')),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='DarkWebScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('findings_count', models.IntegerField(default=0)),
                ('credentials_found', models.IntegerField(default=0)),
                ('mentions_found', models.IntegerField(default=0)),
                ('pastes_found', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='darkweb.darkwebmonitor')),
            ],
            options={
                'ordering': ['-scan_date'],
            },
        ),
    ]
