# Generated by Django 6.0.2 on 2026-03-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('policy', 'Policy Document'), ('sop', 'Standard Operating Procedure (SOP)'), ('evidence', 'Audit Evidence'), ('checklist', 'Compliance Checklist'), ('report', 'Audit Report'), ('vendor_assessment', 'Vendor Risk Assessment'), ('incident_log', 'Incident Response Log'), ('contract', 'Legal Contract / Agreement'), ('diagram', 'Architecture Diagram'), ('other', 'Other Document')], max_length=20),
        ),
    ]
