# Generated by Django 6.0.2 on 2026-03-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_type', models.CharField(choices=[('ISO27001', 'ISO 27001'), ('GDPR', 'GDPR'), ('DPDP', 'DPDP Act (India)'), ('SOC2', 'SOC 2'), ('HIPAA', 'HIPAA'), ('PCIDSS', 'PCI DSS'), ('RBI', 'RBI Guidelines'), ('NPCI', 'NPCI Standards'), ('UIDAI', 'UIDAI/Aadhaar'), ('SEBI', 'SEBI Regulations'), ('IRDAI', 'IRDAI Guidelines')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('suggested_filename', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
