# Generated by Django 6.0.2 on 2026-03-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_compliancerequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='is_authentic',
            field=models.BooleanField(default=True),
        ),
    ]
