# Generated by Django 6.0.2 on 2026-03-21 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('description', models.TextField()),
                ('severity_score', models.FloatField(default=0.0)),
                ('severity_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('published_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('vendor', models.CharField(blank=True, default='', max_length=200)),
                ('product', models.CharField(blank=True, default='', max_length=200)),
                ('attack_vector', models.CharField(blank=True, default='', max_length=50)),
                ('attack_complexity', models.CharField(blank=True, default='', max_length=20)),
                ('references', models.JSONField(blank=True, default=list)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'CVE',
                'verbose_name_plural': 'CVEs',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='CVEControlMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_name', models.CharField(max_length=200)),
                ('framework', models.CharField(max_length=100)),
                ('risk_description', models.TextField()),
                ('mitigation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_mappings', to='cve_engine.cve')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
